# Generated by Django 3.2 on 2021-04-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210423_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='slug',
            field=models.SlugField(null=True, verbose_name='slug'),
        ),
    ]
