# Generated by Django 2.2.4 on 2020-11-22 20:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotional_campaigns', '0001_initial'),
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(decimal_places=2, max_digits=99)])),
                ('final_price', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(decimal_places=2, max_digits=99)])),
                ('genre', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('U', 'unissex')], max_length=100)),
                ('collection', models.CharField(choices=[('AW', 'autumn-winter'), ('SS', 'sprint-summer')], max_length=100)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colors.Color')),
                ('promotional_campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promotional_campaigns.PromotionalCampaign')),
            ],
            options={
                'db_table': 'Clothes',
            },
        ),
    ]
