# Generated by Django 2.2.4 on 2020-11-22 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(decimal_places=2, max_digits=99)]),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(decimal_places=2, max_digits=99)]),
        ),
    ]
