# Generated by Django 2.2.4 on 2020-11-22 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_auto_20201122_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='promotional_campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='promotional_campaigns.PromotionalCampaign'),
        ),
    ]
