# Generated by Django 2.2.4 on 2020-11-23 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_auto_20201122_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='release',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
