# Generated by Django 3.1.5 on 2021-02-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20210201_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('size', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('post_date', models.DateField()),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
    ]
