version: "3.9"
   
services:
  web:
    build: ./
    restart: always
    volumes:
      - static_volume:/usr/src/automation-team-store-challenge/static
    ports:
      - 8000:8000
    # expose: 
      # - "8000"
      # - "6379"
    env_file:
      - env.dev
    depends_on:
      - db
  db:
    image: postgres
    hostname: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  nginx:
    build: .
    ports:
      - 1337:80
    volumes:
      - static_volume:/static_volume
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:

