# Generated by Django 3.1.5 on 2021-02-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_shoe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='status',
            field=models.CharField(blank=True, choices=[('s', 'In Stock'), ('n', 'Non Available'), ('a', 'Available')], default='a', help_text='Shoe availability', max_length=1),
        ),
    ]
