# Generated by Django 3.1.5 on 2021-02-07 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210203_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shoe',
        ),
    ]
