# Generated by Django 3.1.5 on 2021-02-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210207_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='id',
        ),
        migrations.AlterField(
            model_name='shoes',
            name='name',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
