# Generated by Django 3.1.5 on 2021-02-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_shoe_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shoe',
        ),
    ]
