# Generated by Django 2.2.4 on 2020-11-22 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotional_campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalcampaign',
            name='percentage_discount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
