"""
No column names for 10 columns
 A django model generated with django-csvimport csvinspect
    which used OKN messytables to guess data types - may need some manual tweaks!
"""
from django.db import models


class CsvimportData(models.Model):
    ''' Autogenerated model file csvimportdata Sun Feb  7 00:50:56 2021 '''

    col_1 = models.IntegerField(primary_key=True, blank=False, null=False, default=0)
    col_2 = models.CharField(max_length=190, blank=True, default='')
    col_3 = models.DecimalField(max_digits=6, decimal_places=3, blank=True, null=True, default=0)
    col_4 = models.CharField(max_length=5, blank=True, default='')
    col_5 = models.CharField(max_length=9, blank=True, default='')
    col_6 = models.CharField(max_length=9, blank=True, default='')
    col_7 = models.CharField(max_length=42, blank=True, default='')
    col_8 = models.CharField(max_length=165, blank=True, default='')
    col_9 = models.DateTimeField(blank=True, null=True)
    col_10 = models.CharField(max_length=4, blank=True, default='')

    class Meta:
        managed = False
        db_table = u'"csvimport_data"'
