# Generated by Django 3.2.5 on 2021-07-12 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('Esgotado', 'Esgotado'), ('Disponivel', 'Disponivel')], default='Disponivel', max_length=30)),
                ('data_de_lancamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('marca', models.CharField(max_length=30)),
                ('quantidade', models.IntegerField(default=10)),
            ],
        ),
    ]
