# Generated by Django 3.2.5 on 2021-07-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='marca',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
