# Generated by Django 3.2.5 on 2021-07-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_alter_shoes_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='marca',
            field=models.CharField(max_length=30),
        ),
    ]
