# Generated by Django 3.2.5 on 2021-07-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_alter_shoes_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='shoes',
            name='tamanho',
            field=models.IntegerField(default=40),
        ),
    ]
