# Generated by Django 3.2.5 on 2021-07-12 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_auto_20210712_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='tamanho',
            field=models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
