# Generated by Django 2.2.4 on 2020-11-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hex_code', models.CharField(max_length=7, unique=True)),
            ],
            options={
                'db_table': 'Colors',
            },
        ),
    ]
